apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jira-dashboard
  namespace: jira-auto
spec:
  rules:
    - host: jira-dashboard.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jira-dashboard
                port:
                  number: 80
