apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jira-auto

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- servicemonitor.yaml

images:
- name: inikolov98/my-jira-automation
  newName: inikolov98/my-jira-automation
  newTag: 248d3becfc0e1d8772fdc91baf653932b9eb2b77
