apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jira-auto

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - servicemonitor.yaml

images:
  - name: inikolov98/my-jira-automation
    newTag: dev
