apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jira-auto

# - ingress.yaml # temp removed
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- servicemonitor.yaml

images:
- name: inikolov98/my-jira-automation
  newName: inikolov98/my-jira-automation
  newTag: a4447a14a3b4ff8dff5253edc0987f7220d9a8da
