apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jira-auto

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- servicemonitor.yaml

images:
- name: inikolov98/my-jira-automation
  newName: inikolov98/my-jira-automation
  newTag: 328eb73ba00fc50ddbf84c960d16dfabfd99ac06
