apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jira-dashboard
  namespace: jira-auto
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: jira-dashboard
  namespaceSelector:
    matchNames:
      - jira-auto
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
