apiVersion: v1
kind: Service
metadata:
  name: jira-dashboard
  namespace: jira-auto
  labels:
    app: jira-dashboard
spec:
  selector:
    app: jira-dashboard
  ports:
    - name: http
      port: 80
      targetPort: 8000
